src/mahir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('text_carousel/', include('text_carousel.urls')),
]

src/text_carousel/urls.py
"""Make urls available from text carousel app."""

from django.urls import path

from .views import Index

app_name = 'text_carousel'

urlpatterns = [
    path('', Index.as_view(), name='index'),
]

src/text_carousel/models.py
from django.db import models


class BhsaSlots(models.Model):
    """BHSA word nodes (slots)."""
    node = models.IntegerField(primary_key=True, default=0)
    text = models.TextField()

    def __str__(self) -> str:
        """Return text representation of word."""
        return str(self.text)


class BhsaNodes(models.Model):
    """BHSA nodes and some select attributes."""
    node = models.IntegerField(primary_key=True, default=0)
    otype = models.CharField(max_length=20)
    oslots = models.JSONField(default=list)
    book = models.CharField(max_length=30)
    chapter = models.IntegerField(default=1)
    verse = models.IntegerField(default=1)

    def __str__(self) -> str:
        """Return text representation of object."""
        return str(self.oslots)

src/text_carousel/views.py
from django.shortcuts import render
from django.views import View
from django.forms.models import model_to_dict
from django.http import HttpRequest, HttpResponseRedirect

from .models import BhsaSlots, BhsaNodes


class HebrewDataProcessor:

    def __init__(self):
        print('initializing!')
        self.called = 0

    def format_word_data(self, node):
        """Format a collection of nodes into front-end data."""
        self.called += 1
        print('called:', self.called)
        node['oslot_list'] = [
            BhsaSlots.objects.get(pk=id_) for id_ in node['oslots']
        ]
        return node


processor = HebrewDataProcessor()


class Index(View):

    @staticmethod
    def initialize_study_session(request):
        print('Setting up new study session!')
        nodes_list = sorted(
            BhsaNodes.objects.filter(
                book='Genesis',
                chapter=1,
                otype='verse',
            ).values_list('node', flat=True)
        )
        request.session['studySession'] = {
            'position': 0,
            'verses': nodes_list,
        }

    @staticmethod
    def format_word_data(node):
        """Format a collection of nodes into front-end data."""
        node['oslot_list'] = [
            BhsaSlots.objects.get(pk=id_) for id_ in node['oslots']
        ]
        return node

    def get(self, request):

        # SETUP INITIAL STUDY SESSION IF NECESSARY
        if 'studySession' not in request.session:
            self.initialize_study_session(request)

        # PROCESS USER INPUT
        try:
            input = request.GET['input']

            # clear session
            if input == 'ArrowDown':
                print('Flushing session cache!')
                request.session.flush()
                self.initialize_study_session(request)

            # change position
            elif input in {'ArrowRight', 'ArrowLeft'}:

                print('position:', request.session['studySession']['position'])

                session_dict = request.session['studySession']
                if input == 'ArrowRight':
                    session_dict['position'] = min(
                        session_dict['position'] + 1,
                        len(session_dict['verses']) - 1
                    )
                else:
                    session_dict['position'] = max(0, session_dict['position'] - 1)
                request.session['studySession'] = session_dict

            # redirect user to the original page to avoid re-sending get requests on refresh
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        # RENDER THE PAGE
        except KeyError:
            # GET AND RETURN CURRENT PAGE DATA
            position = request.session['studySession']['position']
            verse_id = request.session['studySession']['verses'][position]
            verse_obj = BhsaNodes.objects.get(pk=verse_id)
            bhsa_nodes = processor.format_word_data(
                model_to_dict(verse_obj)
            )
            return render(request, 'text_carousel/index.html', {'bhsaNode': bhsa_nodes})

src/text_carousel/templates/text_carousel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'text_carousel/style.css' %}">
    <title>Text Carousel</title>
</head>
<body>

<div class="interface">
    <div class="textContent">
        <div class="refText">
            <span>
                {{ bhsaNode.book }} {{ bhsaNode.chapter }}:{{ bhsaNode.verse }}
            </span>
        </div>
        <div class="textSlide">
            <span class="hebrewText">
                {% for word in bhsaNode.oslot_list %}{{ word.text }}{% endfor %}
            </span>
        </div>
    </div>
</div>

<form id="statusForm" action="{% url 'text_carousel:index' %}" method="get">
    {% csrf_token %}
    <input id="myInput" type="hidden" name="input" value="">
</form>

<script>

function getHebrewText(){
    return document.getElementsByClassName('hebrewText')[0];
};


document.addEventListener('keydown', (event) => {
    const arrows = [
        'ArrowRight', 'ArrowLeft',
        'ArrowDown', 'ArrowUp',
    ];
    if (arrows.includes(event.key)) {
        let form = document.getElementById("statusForm");
        let input = document.getElementById("myInput");
        input.value = event.key;
        form.submit();
    }
});

</script>

</body>
</html>